#!/bin/bash

# Grayscale
black='#000000'
d5_gray='#0b0b0e'
d4_gray='#17171c'
d3_gray='#2d2f39'
d2_gray='#444655'
d1_gray='#5b5e71'
gray='#71758e'
l1_gray='#8e91a4'
l2_gray='#aaacbb'
l3_gray='#c6c8d2'
l4_gray='#e3e3e8'
white='#f1f1f4'
l1_white='#ffffff'

# Red

d5_red='#1a0200'
d4_red='#4d0500'
d3_red='#800900'
d2_red='#b30c00'
d1_red='#cc0e00'
red='#e60f00'
l1_red='#ff291a'
l2_red='#ff584d'
l3_red='#ff8880'
l4_red='#ffb8b3'

# Orange
d5_orange='#1a0f00'
d4_orange='#331f00'
d3_orange='#663d00'
d2_orange='#995c00'
d1_orange='#ff9500'
orange='#ff9900'
l1_orange='#ffad33'
l2_orange='#ffc266'
l3_orange='#ffd699'
l4_orange='#ffebcc'

# Yellow
d5_yellow='#332a00'
d4_yellow='#665300'
d3_yellow='#997d00'
d2_yellow='#cca700'
d1_yellow='#ffd000'
yellow='#ffda33'
l1_yellow='#ffde4d'
l2_yellow='#ffe880'
l3_yellow='#fff1b3'
l4_yellow='#fffae6'

# Green
d5_green='#001a0f'
d4_green='#00331f'
d3_green='#00663d'
d2_green='#00995c'
d1_green='#00cc7a'
green='#00e68a'
l1_green='#1affa3'
l2_green='#4dffb8'
l3_green='#80ffcc'
l4_green='#b3ffe0'

# Cyan
d5_cyan='#00131a'
d4_cyan='#00384d'
d3_cyan='#005e80'
d2_cyan='#0083b3'
d1_cyan='#00a8e6'
cyan='#00bbff'
l1_cyan='#33c9ff'
l2_cyan='#66d6ff'
l3_cyan='#99e4ff'
l4_cyan='#ccf1ff'

# Blue
d5_blue='#00061a'
d4_blue='#000d33'
d3_blue='#001a66'
d2_blue='#002699'
d1_blue='#0033cc'
blue='#003fff'
l1_blue='#3366ff'
l2_blue='#668cff'
l3_blue='#99b3ff'
l4_blue='#ccd9ff'

# Purple
d5_purple='#0e001a'
d4_purple='#1d0033'
d3_purple='#3a0066'
d2_purple='#570099'
d1_purple='#7400cc'
purple='#9200ff'
l1_purple='#a733ff'
l2_purple='#bd66ff'
l3_purple='#d399ff'
l4_purple='#e9ccff'

# Magenta
d5_magenta='#1a000a'
d4_magenta='#330014'
d3_magenta='#660029'
d2_magenta='#99003d'
d1_magenta='#cc0052'
magenta='#ff0066'
l1_magenta='#ff3385'
l2_magenta='#ff66a3'
l3_magenta='#ff99c2'
l4_magenta='#ffcce0'

# Special
terminal_bg=$d5_gray
editor_bg=$d5_blue
browser_bg=$d5_gray
debug='#ff00ff'

# Indexed colors. Maximum 256
i0=$black
i1=$d1_red
i2=$d1_green
i3=$d1_yellow
i4=$d1_blue
i5=$d1_magenta
i6=$d1_cyan
i7=$l4_gray
i8=$gray
i9=$l1_red
i10=$l1_green
i11=$l1_yellow
i12=$l1_blue
i13=$l1_magenta
i14=$l1_cyan
i15=$l1_white

# ANSI named shortcuts
ansi_black=$i0
ansi_red=$i1
ansi_green=$i2
ansi_yellow=$i3
ansi_blue=$i4
ansi_magenta=$i5
ansi_cyan=$i6
ansi_white=$i7
ansi_brblack=$i8
ansi_brred=$i9
ansi_brgreen=$i10
ansi_bryellow=$i11
ansi_brblue=$i12
ansi_brmagenta=$i13
ansi_brcyan=$i14
ansi_brwhite=$i15

