#!/bin/sh

#-------------------------------------------------------------------------------
# River configuration script
#
# See the river(1), riverctl(1), and rivercarro(1) man pages for complete
# documentation.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Systemd integration
#-------------------------------------------------------------------------------

.config/river/environment

systemd-cat --identifier=river echo "Initializing River"

#-------------------------------------------------------------------------------
# Output configuration
#-------------------------------------------------------------------------------

wlr-randr --output DP-2 --transform 90

#-------------------------------------------------------------------------------
# Style configuration
#-------------------------------------------------------------------------------

# TODO: Get these colors programmatically
# Set background and border color
riverctl background-color 0x0d0d0d
riverctl border-color-focused 0x0d55ea
riverctl border-color-unfocused 0x5d5d6f
riverctl border-color-urgent 0xb30f1f
riverctl border-width 2

#-------------------------------------------------------------------------------
# Input configuration
#-------------------------------------------------------------------------------

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Configure mouse
riverctl input 1133:49295:Logitech_G403_HERO_Gaming_Mouse_Keyboard accel-profile adaptive
riverctl input 1133:49295:Logitech_G403_HERO_Gaming_Mouse_Keyboard pointer-accel 1.0

# Focus should follow the cursor
riverctl focus-follows-cursor normal

#-------------------------------------------------------------------------------
# Key bindings
#-------------------------------------------------------------------------------

# New terminal
# NOTE: The following enables swallowing for terminals:
#   `riverctl map normal Alt N spawn "cage -d alacritty"`
# Unfortunately cage degrades performance of alacritty and doesn't appear to
# work with wezterm.
riverctl map normal Alt N spawn wezterm

# Command menu
riverctl map normal Alt O spawn "wofi --show run"

# Close view
riverctl map normal Alt Q close

# Exit river
riverctl map normal Alt+Shift Q exit

# Focus the next/previous view in the layout stack
riverctl map normal Alt J focus-view next
riverctl map normal Alt K focus-view previous

# Swap the focused view with the next/previous view in the layout stack
riverctl map normal Alt+Shift J swap next
riverctl map normal Alt+Shift K swap previous

# Focus the next/previous output
riverctl map normal Alt H focus-output next
riverctl map normal Alt L focus-output previous

# Send the focused view to the next/previous output
riverctl map normal Alt+Shift H send-to-output next
riverctl map normal Alt+Shift L send-to-output previous

# Bump the focused view to the top of the layout stack
riverctl map normal Alt Tab zoom

# Toggle fullscreen
riverctl map normal Alt F toggle-fullscreen

# Adjust the main ratio of rivercarro
riverctl map normal Alt Down send-layout-cmd rivercarro "main-ratio +0.05"
riverctl map normal Alt Up send-layout-cmd rivercarro "main-ratio -0.05"

# Change layout orientation
# riverctl map normal Alt Up    send-layout-cmd rivercarro "main-location top"
# riverctl map normal Alt Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Alt Left  send-layout-cmd rivercarro "main-location left"
riverctl map normal Alt Right send-layout-cmd rivercarro "main-location top"

# Take a screenshot of a selected rectangle
riverctl map normal Alt P spawn "bin/screenshot-rectangle.sh"

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Focus tag
    riverctl map normal Alt $i set-focused-tags $tags

    # Tag focused view
    riverctl map normal Alt+Shift $i set-view-tags $tags

    # Toggle focus of tag
    riverctl map normal Alt+Control $i toggle-focused-tags $tags

    # Toggle tag of focused view
    # riverctl map normal Alt+Shift+Control $i toggle-view-tags $tags
done

# Toggle float
# riverctl map normal Alt Space toggle-float

# NOTE: This automatically switches the view to floating mode...
# Move views with mouse
# riverctl map-pointer normal Shift BTN_LEFT move-view

# NOTE: This automatically switches the view to floating mode...
# Resize views with mouse
# riverctl map-pointer normal Shift BTN_RIGHT resize-view

# # Super+0 to focus all tags
# # Super+Shift+0 to tag focused view with all tags
# all_tags=$(((1 << 32) - 1))
# riverctl map normal Alt 0 set-focused-tags $all_tags
# riverctl map normal Alt+Shift 0 set-view-tags $all_tags

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
# riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
# riverctl map normal Alt F11 enter-mode passthrough

# Alt+F11 to return to normal mode
# riverctl map passthrough Alt F11 enter-mode normal

# NOTE: This automatically switches the view to floating mode...
# Super+Alt+{H,J,K,L} to move views
# riverctl map normal Super+Alt H move left 100
# riverctl map normal Super+Alt J move down 100
# riverctl map normal Super+Alt K move up 100
# riverctl map normal Super+Alt L move right 100

# NOTE: This automatically switches the view to floating mode...
# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal Super+Alt+Control H snap left
# riverctl map normal Super+Alt+Control J snap down
# riverctl map normal Super+Alt+Control K snap up
# riverctl map normal Super+Alt+Control L snap right

# NOTE: This automatically switches the view to floating mode...
# Super+Alt+Shif+{H,J,K,L} to resize views
# riverctl map normal Super+Alt+Shift H resize horizontal -100
# riverctl map normal Super+Alt+Shift J resize vertical 100
# riverctl map normal Super+Alt+Shift K resize vertical -100
# riverctl map normal Super+Alt+Shift L resize horizontal 100

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
# for mode in normal locked
# do
#     # Eject the optical drive (well if you still have one that is)
#     riverctl map $mode None XF86Eject spawn 'eject -T'
#
#     # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
#     riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
#     riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
#     riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
#
#     # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
#     riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
#     riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
#     riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
#     riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
#
#     # Control screen backlight brighness with light (https://github.com/haikarainen/light)
#     riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
#     riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
# done

#-------------------------------------------------------------------------------
# Status bar configuration
#-------------------------------------------------------------------------------

riverctl spawn ".config/river/statusbar"

#-------------------------------------------------------------------------------
# Layout generator configuration
#-------------------------------------------------------------------------------

# Assign and launch the default layout generator, rivercarro.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
riverctl spawn "rivercarro -inner-gaps 4 -outer-gaps 0 -main-ratio 0.65"

