#!/bin/sh

systemd-cat --identifier=river echo "Initializing Yambar"

#-------------------------------------------------------------------------------
# Status bar configuration
#-------------------------------------------------------------------------------

riverctl spawn yambar
sleep 0.10

riverctl focus-output next

riverctl spawn yambar
sleep 0.10

riverctl focus-output previous

