#!/bin/bash

# https://cssgradient.io/

# Theme
#-------------------------------------------------------------------------------

# Special
debug='#ff00ff'

# Primary
 primary_0='#000610'
 primary_1='#000d1e'
 primary_2='#00152d'
 primary_3='#011d3c'
 primary_4='#01244b'
 primary_5='#022c5a'
 primary_6='#023469'
 primary_7='#023b78'
 primary_8='#034387'
 primary_9='#034b96'
primary_10='#055eb5'
primary_11='#056dc4'
primary_12='#057cd3'
primary_13='#058be1'
primary_14='#059af0'
primary_15='#05aaff'

# Text
 text_0='#001030'
 text_1='#0a1a38'
 text_2='#152540'
 text_3='#203048'
 text_4='#2a3a50'
 text_5='#354558'
 text_6='#405060'
 text_7='#516171'
 text_8='#637383'
 text_9='#748595'
text_10='#8696a6'
text_11='#98a8b8'
text_12='#aabaca'
text_13='#bbcbdb'
text_14='#cddded'
text_15='#dfefff'

# Secondary
 secondary_0='#000e14'
 secondary_1='#02151d'
 secondary_2='#041d27'
 secondary_3='#062431'
 secondary_4='#082c3b'
 secondary_5='#0a3344'
 secondary_6='#0c3b4e'
 secondary_7='#0e4e65'
 secondary_8='#0d5d74'
 secondary_9='#0c6c84'
secondary_10='#0b7b93'
secondary_11='#0a8aa2'
secondary_12='#0999b1'
secondary_13='#08a8c0'
secondary_14='#07b7cf'
secondary_15='#06c6df'

# Gray
 gray_0='#0b0b0e'
 gray_1='#191a20'
 gray_2='#282932'
 gray_3='#363844'
 gray_4='#454757'
 gray_5='#535669'
 gray_6='#62657b'
 gray_7='#71758e'
 gray_8='#71758e'
 gray_9='#83869c'
gray_10='#9598ab'
gray_11='#a7aab9'
gray_12='#babbc8'
gray_13='#cccdd6'
gray_14='#dedfe5'
gray_15='#f1f1f4'

# Red
red_0='#1a0200'
red_1='#4d0500'
red_2='#800900'
red_3='#b30c00'
red_4='#cc0e00'
red_5='#e60f00'
red_6='#ff291a'
red_7='#ff584d'
red_8='#ff8880'
red_9='#ffb8b3'

# Orange
orange_0='#1a0f00'
orange_1='#331f00'
orange_2='#663d00'
orange_3='#995c00'
orange_4='#ff9500'
orange_5='#ff9900'
orange_6='#ffad33'
orange_7='#ffc266'
orange_8='#ffd699'
orange_9='#ffebcc'

# Yellow
yellow_0='#332a00'
yellow_1='#665300'
yellow_2='#997d00'
yellow_3='#cca700'
yellow_4='#ffd000'
yellow_5='#ffda33'
yellow_6='#ffde4d'
yellow_7='#ffe880'
yellow_8='#fff1b3'
yellow_9='#fffae6'

# Green
green_0='#001a0f'
green_1='#00331f'
green_2='#00663d'
green_3='#00995c'
green_4='#00cc7a'
green_5='#00e68a'
green_6='#1affa3'
green_7='#4dffb8'
green_8='#80ffcc'
green_9='#b3ffe0'

# Cyan
cyan_0='#00131a'
cyan_1='#00384d'
cyan_2='#005e80'
cyan_3='#0083b3'
cyan_4='#00a8e6'
cyan_5='#00bbff'
cyan_6='#33c9ff'
cyan_7='#66d6ff'
cyan_8='#99e4ff'
cyan_9='#ccf1ff'

# Blue
blue_0='#00061a'
blue_1='#000d33'
blue_2='#001a66'
blue_3='#002699'
blue_4='#0033cc'
blue_5='#003fff'
blue_6='#3366ff'
blue_7='#668cff'
blue_8='#99b3ff'
blue_9='#ccd9ff'

# Purple
purple_0='#0e001a'
purple_1='#1d0033'
purple_2='#3a0066'
purple_3='#570099'
purple_4='#7400cc'
purple_5='#9200ff'
purple_6='#a733ff'
purple_7='#bd66ff'
purple_8='#d399ff'
purple_9='#e9ccff'

# Magenta
magenta_0='#1a000a'
magenta_1='#330014'
magenta_2='#660029'
magenta_3='#99003d'
magenta_4='#cc0052'
magenta_5='#ff0066'
magenta_6='#ff3385'
magenta_7='#ff66a3'
magenta_8='#ff99c2'
magenta_9='#ffcce0'

# Legacy theme
# NOTE: Should be removed once transition to new theme is complete.
#-------------------------------------------------------------------------------
# Grayscale
black='#000000'
d5_gray='#0b0b0e'
d4_gray='#17171c'
d3_gray='#2d2f39'
d2_gray='#444655'
d1_gray='#5b5e71'
gray='#71758e'
l1_gray='#8e91a4'
l2_gray='#aaacbb'
l3_gray='#c6c8d2'
l4_gray='#e3e3e8'
l5_gray='#f1f1f4'
white='#ffffff'

# Red
d5_red=$red_0
d4_red=$red_1
d3_red=$red_2
d2_red=$red_3
d1_red=$red_4
red=$red_5
l1_red=$red_6
l2_red=$red_7
l3_red=$red_8
l4_red=$red_9

# Orange
d5_orange=$orange_0
d4_orange=$orange_1
d3_orange=$orange_2
d2_orange=$orange_3
d1_orange=$orange_4
orange=$orange_5
l1_orange=$orange_6
l2_orange=$orange_7
l3_orange=$orange_8
l4_orange=$orange_9

# Yellow
d5_yellow=$yellow_0
d4_yellow=$yellow_1
d3_yellow=$yellow_2
d2_yellow=$yellow_3
d1_yellow=$yellow_4
yellow=$yellow_5
l1_yellow=$yellow_6
l2_yellow=$yellow_7
l3_yellow=$yellow_8
l4_yellow=$yellow_9

# Green
d5_green=$green_0
d4_green=$green_1
d3_green=$green_2
d2_green=$green_3
d1_green=$green_4
green=$green_5
l1_green=$green_6
l2_green=$green_7
l3_green=$green_8
l4_green=$green_9

# Cyan
d5_cyan=$cyan_0
d4_cyan=$cyan_1
d3_cyan=$cyan_2
d2_cyan=$cyan_3
d1_cyan=$cyan_4
cyan=$cyan_5
l1_cyan=$cyan_6
l2_cyan=$cyan_7
l3_cyan=$cyan_8
l4_cyan=$cyan_9

# Blue
d5_blue=$blue_0
d4_blue=$blue_1
d3_blue=$blue_2
d2_blue=$blue_3
d1_blue=$blue_4
blue=$blue_5
l1_blue=$blue_6
l2_blue=$blue_7
l3_blue=$blue_8
l4_blue=$blue_9

# Purple
d5_purple=$purple_0
d4_purple=$purple_1
d3_purple=$purple_2
d2_purple=$purple_3
d1_purple=$purple_4
purple=$purple_5
l1_purple=$purple_6
l2_purple=$purple_7
l3_purple=$purple_8
l4_purple=$purple_9

# Magenta
d5_magenta=$magenta_0
d4_magenta=$magenta_1
d3_magenta=$magenta_2
d2_magenta=$magenta_3
d1_magenta=$magenta_4
magenta=$magenta_5
l1_magenta=$magenta_6
l2_magenta=$magenta_7
l3_magenta=$magenta_8
l4_magenta=$magenta_9

# 16 indexed colors
i0=$gray_0
i1=$red_4
i2=$green_3
i3=$orange_6
i4=$primary_10
i5=$magenta_4
i6=$secondary_10
i7=$text_13
i8=$text_10
i9=$red_6
i10=$green_5
i11=$yellow_6
i12=$primary_15
i13=$magenta_6
i14=$secondary_15
i15=$text_15

# ANSI named shortcuts
ansi_black=$i0
ansi_red=$i1
ansi_green=$i2
ansi_yellow=$i3
ansi_blue=$i4
ansi_magenta=$i5
ansi_cyan=$i6
ansi_white=$i7
ansi_brblack=$i8
ansi_brred=$i9
ansi_brgreen=$i10
ansi_bryellow=$i11
ansi_brblue=$i12
ansi_brmagenta=$i13
ansi_brcyan=$i14
ansi_brwhite=$i15

# Themed
terminal_bg=$gray_15
terminal_prompt=$ansi_blue
terminal_text=$text_0

editor_bg=$gray_15
editor_text_normal=$secondary_2

