#!/bin/bash

# https://cssgradient.io/

# Primary
 primary_0='#000610'
 primary_1='#031120'
 primary_2='#071B30'
 primary_3='#0A2640'
 primary_4='#0E3150'
 primary_5='#113C60'
 primary_6='#144670'
 primary_7='#185180'
 primary_8='#1B5C8F'
 primary_9='#1F679F'
primary_10='#2271AF'
primary_11='#257CBF'
primary_12='#2987CF'
primary_13='#2C92DF'
primary_14='#309CEF'
primary_15='#33A7FF'

# Text
text_0='#0E3150'
text_1='#2E4E69'
text_2='#4E6B82'
text_3='#6E889B'
text_4='#8FA4B4'
text_5='#AFC1CD'
text_6='#CFDEE6'
text_7='#EFFBFF'

# Secondary
 secondary_0='#000e14'
 secondary_1='#061a22'
 secondary_2='#0c2730'
 secondary_3='#12343f'
 secondary_4='#18404d'
 secondary_5='#1e4d5c'
 secondary_6='#245a6a'
 secondary_7='#2a6779'
 secondary_8='#307387'
 secondary_9='#368096'
secondary_10='#3c8da4'
secondary_11='#429ab3'
secondary_12='#48a6c1'
secondary_13='#4eb3d0'
secondary_14='#54c0de'
secondary_15='#5acded'

# Grayscale
black='#000000'
d5_gray='#0b0b0e'
d4_gray='#17171c'
d3_gray='#2d2f39'
d2_gray='#444655'
d1_gray='#5b5e71'
gray='#71758e'
l1_gray='#8e91a4'
l2_gray='#aaacbb'
l3_gray='#c6c8d2'
l4_gray='#e3e3e8'
l5_gray='#f1f1f4'
white='#ffffff'

# Red
d5_red='#1a0200'
d4_red='#4d0500'
d3_red='#800900'
d2_red='#b30c00'
d1_red='#cc0e00'
red='#e60f00'
l1_red='#ff291a'
l2_red='#ff584d'
l3_red='#ff8880'
l4_red='#ffb8b3'

# Orange
d5_orange='#1a0f00'
d4_orange='#331f00'
d3_orange='#663d00'
d2_orange='#995c00'
d1_orange='#ff9500'
orange='#ff9900'
l1_orange='#ffad33'
l2_orange='#ffc266'
l3_orange='#ffd699'
l4_orange='#ffebcc'

# Yellow
d5_yellow='#332a00'
d4_yellow='#665300'
d3_yellow='#997d00'
d2_yellow='#cca700'
d1_yellow='#ffd000'
yellow='#ffda33'
l1_yellow='#ffde4d'
l2_yellow='#ffe880'
l3_yellow='#fff1b3'
l4_yellow='#fffae6'

# Green
d5_green='#001a0f'
d4_green='#00331f'
d3_green='#00663d'
d2_green='#00995c'
d1_green='#00cc7a'
green='#00e68a'
l1_green='#1affa3'
l2_green='#4dffb8'
l3_green='#80ffcc'
l4_green='#b3ffe0'

# Desaturated green
ds_green_0='#06130e'
ds_green_1='#0d261c'
ds_green_2='#194d38'
ds_green_3='#267354'
ds_green_4='#339970'
ds_green_5='#39ac7e'
ds_green_6='#53c698'
ds_green_7='#79d2af'
ds_green_8='#9fdfc6'
ds_green_9='#c6ecdd'

# Cyan
d5_cyan='#00131a'
d4_cyan='#00384d'
d3_cyan='#005e80'
d2_cyan='#0083b3'
d1_cyan='#00a8e6'
cyan='#00bbff'
l1_cyan='#33c9ff'
l2_cyan='#66d6ff'
l3_cyan='#99e4ff'
l4_cyan='#ccf1ff'

# Desaturated cyan
ds_cyan_0='#09171c'
ds_cyan_1='#0d1f26'
ds_cyan_2='#132f39'
ds_cyan_3='#193f4d'
ds_cyan_4='#204f60'
ds_cyan_5='#265e73'
ds_cyan_6='#337e99'
ds_cyan_7='#409dbf'
ds_cyan_8='#66b1cc'
ds_cyan_9='#8cc4d9'

# Blue
d5_blue='#00061a'
d4_blue='#000d33'
d3_blue='#001a66'
d2_blue='#002699'
d1_blue='#0033cc'
blue='#003fff'
l1_blue='#3366ff'
l2_blue='#668cff'
l3_blue='#99b3ff'
l4_blue='#ccd9ff'

# Purple
d5_purple='#0e001a'
d4_purple='#1d0033'
d3_purple='#3a0066'
d2_purple='#570099'
d1_purple='#7400cc'
purple='#9200ff'
l1_purple='#a733ff'
l2_purple='#bd66ff'
l3_purple='#d399ff'
l4_purple='#e9ccff'

# Magenta
d5_magenta='#1a000a'
d4_magenta='#330014'
d3_magenta='#660029'
d2_magenta='#99003d'
d1_magenta='#cc0052'
magenta='#ff0066'
l1_magenta='#ff3385'
l2_magenta='#ff66a3'
l3_magenta='#ff99c2'
l4_magenta='#ffcce0'

# Special
terminal_bg=$d5_gray
editor_bg=$primary_0
browser_bg=$d5_purple
debug='#ff00ff'

# 256 indexed colors
i0=$d5_gray
i1=$d1_red
i2=$ds_green_4
i3=$l1_orange
i4=$primary_9
i5=$d1_magenta
i6=$secondary_9
i7=$text_5
i8=$text_2
i9=$l1_red
i10=$green
i11=$l1_yellow
i12=$primary_15
i13=$l1_magenta
i14=$secondary_15
i15=$text_7

# ANSI named shortcuts
ansi_black=$i0
ansi_red=$i1
ansi_green=$i2
ansi_yellow=$i3
ansi_blue=$i4
ansi_magenta=$i5
ansi_cyan=$i6
ansi_white=$i7
ansi_brblack=$i8
ansi_brred=$i9
ansi_brgreen=$i10
ansi_bryellow=$i11
ansi_brblue=$i12
ansi_brmagenta=$i13
ansi_brcyan=$i14
ansi_brwhite=$i15

