#!/bin/bash

# https://cssgradient.io/

# Theme
#-------------------------------------------------------------------------------

# Primary
 primary_0='#000610'
 primary_1='#000d1e'
 primary_2='#00152d'
 primary_3='#011d3c'
 primary_4='#01244b'
 primary_5='#022c5a'
 primary_6='#023469'
 primary_7='#023b78'
 primary_8='#034387'
 primary_9='#034b96'
primary_10='#055eb5'
primary_11='#056dc4'
primary_12='#057cd3'
primary_13='#058be1'
primary_14='#059af0'
primary_15='#05aaff'

# Text
 text_0='#001030'
 text_1='#0a1a38'
 text_2='#152540'
 text_3='#203048'
 text_4='#2a3a50'
 text_5='#354558'
 text_6='#405060'
 text_7='#516171'
 text_8='#637383'
 text_9='#748595'
text_10='#8696a6'
text_11='#98a8b8'
text_12='#aabaca'
text_13='#bbcbdb'
text_14='#cddded'
text_15='#dfefff'

# Secondary
 secondary_0='#000e14'
 secondary_1='#02151d'
 secondary_2='#041d27'
 secondary_3='#062431'
 secondary_4='#082c3b'
 secondary_5='#0a3344'
 secondary_6='#0c3b4e'
 secondary_7='#0e4e65'
 secondary_8='#0d5d74'
 secondary_9='#0c6c84'
secondary_10='#0b7b93'
secondary_11='#0a8aa2'
secondary_12='#0999b1'
secondary_13='#08a8c0'
secondary_14='#07b7cf'
secondary_15='#06c6df'

# Gray
 gray_0='#0b0b0e'
 gray_1='#191a20'
 gray_2='#282932'
 gray_3='#363844'
 gray_4='#454757'
 gray_5='#535669'
 gray_6='#62657b'
 gray_7='#71758e'
 gray_8='#71758e'
 gray_9='#83869c'
gray_10='#9598ab'
gray_11='#a7aab9'
gray_12='#babbc8'
gray_13='#cccdd6'
gray_14='#dedfe5'
gray_15='#f1f1f4'

# Legacy theme
#-------------------------------------------------------------------------------
# Grayscale
black='#000000'
d5_gray='#0b0b0e'
d4_gray='#17171c'
d3_gray='#2d2f39'
d2_gray='#444655'
d1_gray='#5b5e71'
gray='#71758e'
l1_gray='#8e91a4'
l2_gray='#aaacbb'
l3_gray='#c6c8d2'
l4_gray='#e3e3e8'
l5_gray='#f1f1f4'
white='#ffffff'

# Red
d5_red='#1a0200'
d4_red='#4d0500'
d3_red='#800900'
d2_red='#b30c00'
d1_red='#cc0e00'
red='#e60f00'
l1_red='#ff291a'
l2_red='#ff584d'
l3_red='#ff8880'
l4_red='#ffb8b3'

# Orange
d5_orange='#1a0f00'
d4_orange='#331f00'
d3_orange='#663d00'
d2_orange='#995c00'
d1_orange='#ff9500'
orange='#ff9900'
l1_orange='#ffad33'
l2_orange='#ffc266'
l3_orange='#ffd699'
l4_orange='#ffebcc'

# Yellow
d5_yellow='#332a00'
d4_yellow='#665300'
d3_yellow='#997d00'
d2_yellow='#cca700'
d1_yellow='#ffd000'
yellow='#ffda33'
l1_yellow='#ffde4d'
l2_yellow='#ffe880'
l3_yellow='#fff1b3'
l4_yellow='#fffae6'

# Green
d5_green='#001a0f'
d4_green='#00331f'
d3_green='#00663d'
d2_green='#00995c'
d1_green='#00cc7a'
green='#00e68a'
l1_green='#1affa3'
l2_green='#4dffb8'
l3_green='#80ffcc'
l4_green='#b3ffe0'

# Desaturated green
ds_green_0='#06130e'
ds_green_1='#0d261c'
ds_green_2='#194d38'
ds_green_3='#267354'
ds_green_4='#339970'
ds_green_5='#39ac7e'
ds_green_6='#53c698'
ds_green_7='#79d2af'
ds_green_8='#9fdfc6'
ds_green_9='#c6ecdd'

# Cyan
d5_cyan='#00131a'
d4_cyan='#00384d'
d3_cyan='#005e80'
d2_cyan='#0083b3'
d1_cyan='#00a8e6'
cyan='#00bbff'
l1_cyan='#33c9ff'
l2_cyan='#66d6ff'
l3_cyan='#99e4ff'
l4_cyan='#ccf1ff'

# Desaturated cyan
ds_cyan_0='#09171c'
ds_cyan_1='#0d1f26'
ds_cyan_2='#132f39'
ds_cyan_3='#193f4d'
ds_cyan_4='#204f60'
ds_cyan_5='#265e73'
ds_cyan_6='#337e99'
ds_cyan_7='#409dbf'
ds_cyan_8='#66b1cc'
ds_cyan_9='#8cc4d9'

# Blue
d5_blue='#00061a'
d4_blue='#000d33'
d3_blue='#001a66'
d2_blue='#002699'
d1_blue='#0033cc'
blue='#003fff'
l1_blue='#3366ff'
l2_blue='#668cff'
l3_blue='#99b3ff'
l4_blue='#ccd9ff'

# Purple
d5_purple='#0e001a'
d4_purple='#1d0033'
d3_purple='#3a0066'
d2_purple='#570099'
d1_purple='#7400cc'
purple='#9200ff'
l1_purple='#a733ff'
l2_purple='#bd66ff'
l3_purple='#d399ff'
l4_purple='#e9ccff'

# Magenta
d5_magenta='#1a000a'
d4_magenta='#330014'
d3_magenta='#660029'
d2_magenta='#99003d'
d1_magenta='#cc0052'
magenta='#ff0066'
l1_magenta='#ff3385'
l2_magenta='#ff66a3'
l3_magenta='#ff99c2'
l4_magenta='#ffcce0'

# Special
terminal_bg=$d5_gray
debug='#ff00ff'

# 256 indexed colors
i0=$d5_gray
i1=$d1_red
i2=$ds_green_4
i3=$l1_orange
i4=$primary_9
i5=$d1_magenta
i6=$secondary_9
i7=$text_10
i8=$text_4
i9=$l1_red
i10=$green
i11=$l1_yellow
i12=$primary_15
i13=$l1_magenta
i14=$secondary_15
i15=$text_15

# ANSI named shortcuts
ansi_black=$i0
ansi_red=$i1
ansi_green=$i2
ansi_yellow=$i3
ansi_blue=$i4
ansi_magenta=$i5
ansi_cyan=$i6
ansi_white=$i7
ansi_brblack=$i8
ansi_brred=$i9
ansi_brgreen=$i10
ansi_bryellow=$i11
ansi_brblue=$i12
ansi_brmagenta=$i13
ansi_brcyan=$i14
ansi_brwhite=$i15

